<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>5RAHWFC7UDPR</MasterId>
  <Id>5RAHWFC7UDPR</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>8.0.8.0</AppVersion>
      <Modifier>2466323509031207936</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>5RAHWFFD3I96</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <Caption>帮助中心</Caption>
              <Description>帮助中心</Description>
              <FormName>应用入门中心</FormName>
              <FormNumber>bas_appstarted</FormNumber>
              <Parameter>{"caption":{"zh_CN":"帮助中心"}}</Parameter>
              <Id>5RDOW9S/H33#hpce</Id>
              <Seq>32766</Seq>
              <FormId>/WXHVRP15OWF</FormId>
              <IconShortcut>/icons/pc/entrance/helpcentre.png</IconShortcut>
              <Visible>0</Visible>
              <ParentId>5RAHWFC7UDPR</ParentId>
              <VectorImage>kdfont kdfont-tishixinxi_l</VectorImage>
              <Name>帮助中心</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
          </AppMenus>
          <Isv>fyl6</Isv>
          <Number>fyl6_report</Number>
          <Id>5RAHWFC7UDPR</Id>
          <BizCloudID>566MO8VGPWYH</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>fyl6_report_apphome</MainFormNumber>
              <Description>这是一个新的应用</Description>
              <DbRoute>secd</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>fyl6_report</Number>
              <Id>5RAHWFC7UDPR</Id>
              <Seq>10</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
              <Visible>1</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>报表_应用首页</MainFormName>
              <Version>8.0.8.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>5RAHWHMFYEIE</MainFormID>
              <Name>报表</Name>
              <SimpleNumber/>
              <UserType>,1,</UserType>
              <DeployStatus>2</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>secd</DbRoute>
      <Isv>fyl6</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>fyl6_report</Number>
      <IndustryId>0</IndustryId>
      <Id>5RAHWFC7UDPR</Id>
      <Seq>10</Seq>
      <CreateDate>1777571655114</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>566MO8VGPWYH</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1777986561881</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>报表_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>2466323509031207936</Creater>
      <MainFormID>5RAHWHMFYEIE</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
